# SPDX-License-Identifier: GPL-2.0

XDP_TARGETS := xdp_netem.bpf
BPF_SKEL_TARGETS := $(XDP_TARGETS)

XDP_OBJ_INSTALL :=

TOOL_NAME := xdp-netem
MAN_PAGE :=
TEST_FILE :=
USER_TARGETS := xdp-netem

LIB_DIR := ../lib

include $(LIB_DIR)/common.mk
