# SPDX-License-Identifier: GPL-2.0

XDP_TARGETS := xdp_netem.bpf xdp_netem_lb.bpf xdp_forward.bpf
BPF_SKEL_TARGETS := $(XDP_TARGETS)

XDP_OBJ_INSTALL :=

TOOL_NAME := xdp-netem xdp-netem-lb
MAN_PAGE :=
TEST_FILE :=
USER_TARGETS := xdp-netem xdp-netem-lb

LIB_DIR := ../lib

include $(LIB_DIR)/common.mk
